drop table if exists TEMPORALS;

create table TEMPORALS (
	ID				BIGINT PRIMARY KEY,
	DOB_DT			DATE NULL,
	OPENING_TIME	TIME NULL,
	TIMESTAMP_FIX	TIMESTAMP NULL,
	TIMESTAMP_TS	TIMESTAMP NULL,
	ZONE_ID			VARCHAR(100),
	ZONE_OFFSET		VARCHAR(50)
);